FROM golang:1.23-alpine

WORKDIR /app

RUN apk add --no-cache git && \
    go install github.com/pressly/goose/v3/cmd/goose@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD go test -v ./...