-- +goose Up
CREATE TABLE IF NOT EXISTS public.brand (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name text NOT NULL UNIQUE,
    CONSTRAINT brand_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.category (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type int NOT NULL,
	name text NOT NULL,
	CONSTRAINT category_pk PRIMARY KEY (id)
);

-- Column comments
COMMENT ON COLUMN public.category.type IS 'Тип категория - 1 - одежда, 2 - обувь';

CREATE TABLE IF NOT EXISTS public.items (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    brand_id int NOT NULL,
	name text NOT NULL,
	description text NOT NULL,
    sex int NOT NUll,
    category_id int NOT NULL,
	price int NOT NULL,
	discount int NULL,
    outer_link text NOT NULL,
    created_at timestamp WITHOUT TIME ZONE NOT NULL,
    updated_at timestamp WITHOUT TIME ZONE NULL,
	CONSTRAINT items_pk PRIMARY KEY (id),
    FOREIGN KEY (brand_id) REFERENCES public.brand (id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES public.category (id) ON DELETE CASCADE
);

-- Column comments
COMMENT ON COLUMN public.items.sex IS 'Пол 1 - мужской, 2 - женский, 3 - унисекс';

CREATE TABLE IF NOT EXISTS public.images (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id int NOT NULL,
	object_id text NOT NULL UNIQUE,
    uploaded_at timestamp WITHOUT TIME ZONE NULL,
	CONSTRAINT images_pk PRIMARY KEY (id),
    FOREIGN KEY (item_id) REFERENCES public.items (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.temp_images (
	id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_id text NOT NULL UNIQUE,
    uploaded_at timestamp WITHOUT TIME ZONE NULL,
	CONSTRAINT temp_images_pk PRIMARY KEY (id)
);

-- Inset data
-- Category
INSERT INTO public.category (type, name) VALUES ('1','Верхняя одежда');
INSERT INTO public.category (type, name) VALUES ('1','Джинсы и блюки');
INSERT INTO public.category (type, name) VALUES ('1','Лонгсливы');
INSERT INTO public.category (type, name) VALUES ('1','Рубашки');
INSERT INTO public.category (type, name) VALUES ('1','Рубашки и овершоты');
INSERT INTO public.category (type, name) VALUES ('1','Свитеры и кардиганы');
INSERT INTO public.category (type, name) VALUES ('1','Толстовки');
INSERT INTO public.category (type, name) VALUES ('1','Футболки и поло');
INSERT INTO public.category (type, name) VALUES ('1','Шорты');
INSERT INTO public.category (type, name) VALUES ('1','Юбки');
INSERT INTO public.category (type, name) VALUES ('1','Жилеты');
INSERT INTO public.category (type, name) VALUES ('2','Кроссовки');
INSERT INTO public.category (type, name) VALUES ('2','Кеды');
INSERT INTO public.category (type, name) VALUES ('2','Ботинки');
INSERT INTO public.category (type, name) VALUES ('2','Сандали');
INSERT INTO public.category (type, name) VALUES ('2','Шлепанцы');

-- Brands
INSERT INTO public.brand (name) VALUES ('Gleb Kostin .Solutions');
INSERT INTO public.brand (name) VALUES ('Mizuno');
INSERT INTO public.brand (name) VALUES ('Daze');

-- +goose Down
DROP TABLE images;
DROP TABLE items;
DROP TABLE brand;
DROP TABLE category;
DROP TABLE temp_images;